// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr1f2eR-IIi0ncfANsK_fsM_f3_fsNnhI',
    appId: '1:666662171875:web:c55786d96b158b4ed6c1d6',
    messagingSenderId: '666662171875',
    projectId: 'foodigy-app',
    authDomain: 'foodigy-app.firebaseapp.com',
    databaseURL: 'https://foodigy-app-default-rtdb.firebaseio.com',
    storageBucket: 'foodigy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFQi9iOOzYD78qy1F4VM4T7VuArvPD7cg',
    appId: '1:666662171875:android:627547475ad1f905d6c1d6',
    messagingSenderId: '666662171875',
    projectId: 'foodigy-app',
    databaseURL: 'https://foodigy-app-default-rtdb.firebaseio.com',
    storageBucket: 'foodigy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV9QPQo0-7yoS9bAU_vmY59S0yo5RJpE4',
    appId: '1:666662171875:ios:9d6ec12c623d4b70d6c1d6',
    messagingSenderId: '666662171875',
    projectId: 'foodigy-app',
    databaseURL: 'https://foodigy-app-default-rtdb.firebaseio.com',
    storageBucket: 'foodigy-app.appspot.com',
    androidClientId: '666662171875-cafp5q9ltkoh7teogich3ct1s51llld7.apps.googleusercontent.com',
    iosClientId: '666662171875-vrngjc7jbk446plf22t595dbntrm205d.apps.googleusercontent.com',
    iosBundleId: 'com.foodigy.consumer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV9QPQo0-7yoS9bAU_vmY59S0yo5RJpE4',
    appId: '1:666662171875:ios:05c383903eb3eea2d6c1d6',
    messagingSenderId: '666662171875',
    projectId: 'foodigy-app',
    databaseURL: 'https://foodigy-app-default-rtdb.firebaseio.com',
    storageBucket: 'foodigy-app.appspot.com',
    androidClientId: '666662171875-cafp5q9ltkoh7teogich3ct1s51llld7.apps.googleusercontent.com',
    iosClientId: '666662171875-k6lim9o7iiqfftoca5qbmtcd9jm4keke.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodigy',
  );
}
